# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="This is the name you'll use to reference this experiment in code and templates.", max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=False)),
                ('variants', models.TextField(help_text="Provide a list of all variants you'd like to test, one variant name per line")),
            ],
        ),
    ]
